import {
  AffixProps,
  AlertProps,
  AnchorLinkProps,
  AnchorProps,
  AppProps,
  AutoCompleteProps,
  AvatarProps,
  BackTopProps,
  BadgeProps,
  BreadcrumbItemProps,
  BreadcrumbProps,
  ButtonProps,
  CalendarProps,
  CardProps,
  CarouselProps,
  CascaderProps,
  CheckboxOptionType,
  CheckboxProps,
  CheckboxRef,
  ColProps,
  CollapsePanelProps,
  CollapseProps,
  ColorPickerProps,
  ThemeConfig,
  DatePickerProps,
  DescriptionsProps,
  DividerProps,
  DrawerProps,
  DropdownProps,
  EmptyProps,
  FloatButtonGroupProps,
  FloatButtonProps,
  FormInstance,
  FormItemProps,
  FormListFieldData,
  FormListOperation,
  FormProps,
  ImageProps,
  InputProps,
  InputRef,
  InputNumberProps,
  LayoutProps,
  SiderProps,
  ListProps,
  MentionProps,
  MenuItemProps,
  MenuProps,
  MenuRef,
  MenuTheme,
  SubMenuProps,
  ModalFuncProps,
  ModalProps,
  PaginationProps,
  PopconfirmProps,
  PopoverProps,
  ProgressProps,
  QRCodeProps,
  QRPropsCanvas,
  QRPropsSvg,
  RadioChangeEvent,
  RadioGroupProps,
  RadioProps,
  RateProps,
  ResultProps,
  RowProps,
  SegmentedProps,
  RefSelectProps,
  SelectProps,
  SkeletonProps,
  SliderSingleProps,
  SpaceProps,
  SpinProps,
  CountdownProps,
  StatisticProps,
  StepProps,
  StepsProps,
  SwitchProps,
  TableProps,
  TablePaginationConfig,
  TableColumnGroupType,
  TableColumnProps,
  TableColumnType,
  TableColumnsType,
  TabPaneProps,
  TabsProps,
  TagProps,
  TagType,
  TimePickerProps,
  TimeRangePickerProps,
  TimelineItemProps,
  TimelineProps,
  TooltipProps,
  TourProps,
  TourStepProps,
  TransferProps,
  TreeDataNode,
  TreeNodeProps,
  TreeProps,
  TreeSelectProps,
  TypographyProps,
  UploadFile,
  UploadProps,
  WatermarkProps,
} from 'antd';
import { TextAreaProps } from 'antd/es/input';
import { TextAreaRef } from 'antd/es/input/TextArea';
import { CirclePickerProps } from 'react-color';

export type LibsElementsProps = {
  Affix: AffixProps;
  InputNumber: InputNumberProps;
  Input: InputProps & InputRef;
  DatePicker: DatePickerProps;
  Select: SelectProps;
  Rate: RateProps;
  TextArea: TextAreaProps & TextAreaRef;
  CirclePicker: CirclePickerProps;
  // 계속 추가할 예정
};
