name: CD

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  #Now we have got the access of EC2 and we will start the deploy .
  workflow_dispatch:

jobs:
  SSH:
    # The type of runner that the job will run on..
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: ssh to ec2
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.EC2_SSH_KEY  }}
          host: ${{ secrets.HOST_DNS  }}
          username: ${{ secrets.USER_NAME  }}
          script: |
            sudo chown -R $USER:$USER .
            sudo su
            cd Closet/back
            git config --global --add safe.directory /home/ubuntu/Closet
            git pull
            npm ci
            npx pm2 reload all

      #   run: |
      #     echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
      #     ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME}
      #     'DIR="/Closet/back"'

      # - name: root directory
      #   run: |
      #     sudo su
      #     cd Closet/back

      # - name: checkout branch
      #   run: git checkout main

      # - name: reset git log
      #   run: git reset --hard

      # - name: pull repository
      #   run: git pull

      # - name: install package
      #   run: npm i

      # - name: reload server
      #   run: npx pm2 reload all
